In [143]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [144]:
df=pd.read_csv("googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [145]:
df1=pd.read_csv("googleplaystore_user_reviews.csv")
df1.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [146]:
df.shape
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [147]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [148]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [149]:
df[df["Android Ver"].isnull()]
df[df["Current Ver"].isnull()]
df[df["Content Rating"].isnull()]
df[df["Type"].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,NaN,0,Varies with device,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [150]:
df["Category"].unique()
df[df["Category"]=="PERSONALIZATION"].shape[0]

392

In [151]:
df.dropna(subset=["Type","Android Ver","Current Ver","Content Rating"],inplace=True)
df.isnull().sum()

App                  0
Category             0
Rating            1469
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          0
Android Ver          0
dtype: int64

In [152]:
mean=df["Rating"].mean()
df.fillna({"Rating": mean},inplace=True)
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [153]:
df.duplicated().sum()

np.int64(483)

In [154]:
df["Type"].unique()

<StringArray>
['Free', 'Paid']
Length: 2, dtype: str

In [155]:
df["Reviews"].unique()
df["Reviews"]=pd.to_numeric(df["Reviews"])

In [156]:
df["Size"].unique()
df["Price"].unique()

<StringArray>
[      '0',   '$4.99',   '$3.99',   '$6.99',   '$1.49',   '$2.99',   '$7.99',
   '$5.99',   '$3.49',   '$1.99',   '$9.99',   '$7.49',   '$0.99',   '$9.00',
   '$5.49',  '$10.00',  '$24.99',  '$11.99',  '$79.99',  '$16.99',  '$14.99',
   '$1.00',  '$29.99',  '$12.99',   '$2.49',  '$10.99',   '$1.50',  '$19.99',
  '$15.99',  '$33.99',  '$74.99',  '$39.99',   '$3.95',   '$4.49',   '$1.70',
   '$8.99',   '$2.00',   '$3.88',  '$25.99', '$399.99',  '$17.99', '$400.00',
   '$3.02',   '$1.76',   '$4.84',   '$4.77',   '$1.61',   '$2.50',   '$1.59',
   '$6.49',   '$1.29',   '$5.00',  '$13.99', '$299.99', '$379.99',  '$37.99',
  '$18.99', '$389.99',  '$19.90',   '$8.49',   '$1.75',  '$14.00',   '$4.85',
  '$46.99', '$109.99', '$154.99',   '$3.08',   '$2.59',   '$4.80',   '$1.96',
  '$19.40',   '$3.90',   '$4.59',  '$15.46',   '$3.04',   '$4.29',   '$2.60',
   '$3.28',   '$4.60',  '$28.99',   '$2.95',   '$2.90',   '$1.97', '$200.00',
  '$89.99',   '$2.56',  '$30.99',   '$3.61', '$394.99',   '$1.26',   '$1.20',
   '$1.04']
Length: 92, dtype: str

In [157]:
df["Price"]=df["Price"].str.replace(r'[\$]','',regex=True)
df["Price"]=pd.to_numeric(df["Price"])

In [158]:
df["Installs"].unique()
df["Installs"]=df["Installs"].str.replace(r'[\+,]','',regex=True)
df["Installs"]=pd.to_numeric(df["Installs"])
df.duplicated().sum()

np.int64(483)

In [159]:
df["Size"].value_counts()
df["Size"]=df["Size"].replace("Varies with device",np.nan)

In [160]:
def convert_size(size):
    if pd.isna(size):
        return np.nan

    if "M" in size:
        return float(size.replace("M", ""))

    if "k" in size:
        return float(size.replace("k", "")) / 1024

    return np.nan

In [161]:
df["Size"] = df["Size"].apply(convert_size)
df.info()

<class 'pandas.DataFrame'>
Index: 10829 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10829 non-null  str
 1   Category        10829 non-null  str
 2   Rating          10829 non-null  float64
 3   Reviews         10829 non-null  int64
 4   Size            9135 non-null   float64
 5   Installs        10829 non-null  int64
 6   Type            10829 non-null  str
 7   Price           10829 non-null  float64
 8   Content Rating  10829 non-null  str
 9   Genres          10829 non-null  str
 10  Last Updated    10829 non-null  str
 11  Current Ver     10829 non-null  str
 12  Android Ver     10829 non-null  str
dtypes: float64(3), int64(2), str(8)
memory usage: 1.2 MB

In [162]:
df["Size"]=df["Size"].fillna(df["Size"].median())
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [163]:
df["Last Updated"]=pd.to_datetime(df["Last Updated"])
df["Last_updated_year"]=df["Last Updated"].dt.year
df["Last_updated_month"]=df["Last Updated"].dt.month

In [164]:
df.drop('Last Updated',axis=1,inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 10829 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   App                 10829 non-null  str
 1   Category            10829 non-null  str
 2   Rating              10829 non-null  float64
 3   Reviews             10829 non-null  int64
 4   Size                10829 non-null  float64
 5   Installs            10829 non-null  int64
 6   Type                10829 non-null  str
 7   Price               10829 non-null  float64
 8   Content Rating      10829 non-null  str
 9   Genres              10829 non-null  str
 10  Current Ver         10829 non-null  str
 11  Android Ver         10829 non-null  str
 12  Last_updated_year   10829 non-null  int32
 13  Last_updated_month  10829 non-null  int32
dtypes: float64(3), int32(2), int64(2), str(7)
memory usage: 1.2 MB

In [165]:
df.drop(['App','Android Ver','Current Ver'],axis=1,inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 10829 entries, 0 to 10840
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Category            10829 non-null  str
 1   Rating              10829 non-null  float64
 2   Reviews             10829 non-null  int64
 3   Size                10829 non-null  float64
 4   Installs            10829 non-null  int64
 5   Type                10829 non-null  str
 6   Price               10829 non-null  float64
 7   Content Rating      10829 non-null  str
 8   Genres              10829 non-null  str
 9   Last_updated_year   10829 non-null  int32
 10  Last_updated_month  10829 non-null  int32
dtypes: float64(3), int32(2), int64(2), str(4)
memory usage: 930.6 KB

In [166]:
for col in df.columns:
    print(col)
    print("unique:",df[col].unique())
    print(df[col].value_counts().head())

Category
unique: <StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION']
Length: 33, dtype: str
Category
FAMILY      1968
GAME        1144
TOOLS        841
MEDICAL      463
BUSINESS     460
Name: count, dtype: int64
Rating
unique: [4.1        3.9        4.7        4.5        4.3        4.4
 3.8        4.2        4.6        4.         4.19183761 4.8
 4.9        3.6        3.7        3.2        3.3        3.4
 3.5        3.1        5.         2.6        3.         1.9
 2.5        2.8        2.7        1.         2.9        2.3
 2.2        1.7        2.         1.8        2.4        1.6
 2.1        1.4        1.5        1.2       ]
Rating
4.191838    1469
4.400000    1108
4.300000    1076
4.500000    1037
4.200000     951
Name: count, dtype: int64
Reviews
unique: [   159    967  87510 ...    603   1195 398307]
Reviews
0    594
1    271
2    214
3    175
4    137
Name: count, dtype: int64
Size
unique: [1.90000000e+01 1.40000000e+01 8.70000000e+00 2.50000000e+01
 2.80000000e+00 5.60000000e+00 2.90000000e+01 3.30000000e+01
 3.10000000e+00 2.80000000e+01 1.20000000e+01 2.00000000e+01
 2.10000000e+01 3.70000000e+01 5.50000000e+00 1.70000000e+01
 3.90000000e+01 3.10000000e+01 4.20000000e+00 7.00000000e+00
 2.30000000e+01 6.00000000e+00 6.10000000e+00 4.60000000e+00
 9.20000000e+00 5.20000000e+00 1.10000000e+01 2.40000000e+01
 1.30000000e+01 9.40000000e+00 1.50000000e+01 1.00000000e+01
 1.20000000e+00 2.60000000e+01 8.00000000e+00 7.90000000e+00
 5.60000000e+01 5.70000000e+01 3.50000000e+01 5.40000000e+01
 1.96289062e-01 3.60000000e+00 5.70000000e+00 8.60000000e+00
 2.40000000e+00 2.70000000e+01 2.70000000e+00 2.50000000e+00
 1.60000000e+01 3.40000000e+00 8.90000000e+00 3.90000000e+00
 2.90000000e+00 3.80000000e+01 3.20000000e+01 5.40000000e+00
 1.80000000e+01 1.10000000e+00 2.20000000e+00 4.50000000e+00
 9.80000000e+00 5.20000000e+01 9.00000000e+00 6.70000000e+00
 3.00000000e+01 2.60000000e+00 7.10000000e+00 3.70000000e+00
 2.20000000e+01 7.40000000e+00 6.40000000e+00 3.20000000e+00
 8.20000000e+00 9.90000000e+00 4.90000000e+00 9.50000000e+00
 5.00000000e+00 5.90000000e+00 7.30000000e+01 6.80000000e+00
 3.50000000e+00 4.00000000e+00 2.30000000e+00 7.20000000e+00
 2.10000000e+00 4.20000000e+01 7.30000000e+00 9.10000000e+00
 5.50000000e+01 2.24609375e-02 6.50000000e+00 1.50000000e+00
 7.50000000e+00 5.10000000e+01 4.10000000e+01 4.80000000e+01
 8.50000000e+00 4.60000000e+01 8.30000000e+00 4.30000000e+00
 4.70000000e+00 3.30000000e+00 4.00000000e+01 7.80000000e+00
 8.80000000e+00 6.60000000e+00 5.10000000e+00 6.10000000e+01
 6.60000000e+01 7.71484375e-02 8.40000000e+00 1.15234375e-01
 4.40000000e+01 6.78710938e-01 1.60000000e+00 6.20000000e+00
 1.75781250e-02 5.30000000e+01 1.40000000e+00 3.00000000e+00
 5.80000000e+00 3.80000000e+00 9.60000000e+00 4.50000000e+01
 6.30000000e+01 4.90000000e+01 7.70000000e+01 4.40000000e+00
 4.80000000e+00 7.00000000e+01 6.90000000e+00 9.30000000e+00
 8.10000000e+00 3.60000000e+01 8.40000000e+01 9.70000000e+01
 2.00000000e+00 1.90000000e+00 1.80000000e+00 5.30000000e+00
 4.70000000e+01 5.42968750e-01 5.13671875e-01 7.60000000e+01
 7.60000000e+00 5.90000000e+01 9.70000000e+00 7.80000000e+01
 7.20000000e+01 4.30000000e+01 7.70000000e+00 6.30000000e+00
 3.26171875e-01 3.40000000e+01 9.30000000e+01 6.50000000e+01
 7.90000000e+01 1.00000000e+02 5.80000000e+01 5.00000000e+01
 6.80000000e+01 6.40000000e+01 6.70000000e+01 6.00000000e+01
 9.40000000e+01 2.26562500e-01 9.90000000e+01 6.09375000e-01
 9.50000000e+01 8.30078125e-03 4.00390625e-02 2.85156250e-01
 8.00000000e+01 1.70000000e+00 7.40000000e+01 6.20000000e+01
 6.90000000e+01 7.50000000e+01 9.80000000e+01 8.50000000e+01
 8.20000000e+01 9.60000000e+01 8.70000000e+01 7.10000000e+01
 8.60000000e+01 9.10000000e+01 8.10000000e+01 9.20000000e+01
 8.30000000e+01 8.80000000e+01 6.87500000e-01 8.41796875e-01
 8.77929688e-01 3.69140625e-01 2.59765625e-01 3.66210938e-01
 1.30000000e+00 9.52148438e-01 9.57031250e-01 4.10000000e+00
 8.90000000e+01 6.79687500e-01 5.31250000e-01 5.12695312e-01
 8.98437500e-01 7.60742188e-01 8.33007812e-01 7.03125000e-01
 6.96289062e-01 7.53906250e-01 3.10546875e-01 5.66406250e-02
 2.35351562e-01 1.91406250e-01 8.36914062e-01 4.98046875e-02
 9.30664062e-01 8.44726562e-01 2.45117188e-01 9.08203125e-01
 5.27343750e-01 3.05664062e-01 7.28515625e-01 1.98242188e-01
 2.53906250e-02 3.06640625e-01 2.33398438e-01 3.62304688e-01
 2.14843750e-01 7.12890625e-01 7.38281250e-01 8.88671875e-02
 2.86132812e-01 1.66015625e-02 7.22656250e-02 1.36718750e-02
 3.09570312e-01 7.61718750e-02 9.02343750e-01 8.80859375e-01
 7.98828125e-01 7.91015625e-02 9.16992188e-01 1.65039062e-01
 4.39453125e-02 4.63867188e-01 9.42382812e-01 9.00000000e+01
 5.32226562e-01 5.95703125e-02 2.76367188e-01 6.39648438e-01
 6.97265625e-01 9.08203125e-02 8.51562500e-01 1.18164062e-01
 3.14453125e-01 1.00000000e+00 9.53125000e-01 1.67968750e-01
 2.32421875e-01 5.36132812e-01 2.01171875e-01 9.31640625e-01
 4.33593750e-01 7.00195312e-01 2.05078125e-01 5.94726562e-01
 3.00781250e-01 6.88476562e-01 2.98828125e-01 8.82812500e-01
 4.61914062e-01 1.70898438e-01 3.41796875e-01 3.74023438e-01
 4.43359375e-01 4.11132812e-01 6.83593750e-02 7.92968750e-01
 4.31640625e-01 8.22265625e-01 4.07226562e-01 4.02343750e-01
 4.48242188e-01 4.66796875e-01 3.27148438e-01 7.63671875e-01
 7.04101562e-01 4.19921875e-01 4.18945312e-01 1.87500000e-01
 1.95312500e-01 4.49218750e-01 7.10937500e-01 4.84375000e-01
 7.96875000e-01 4.04296875e-01 4.94140625e-01 8.66210938e-01
 5.98632812e-01 2.37304688e-01 5.55664062e-01 7.59765625e-01
 6.66992188e-01 5.78125000e-01 3.11523438e-01 1.81640625e-01
 8.20312500e-01 6.31835938e-01 1.86523438e-01 3.64257812e-01
 4.26757812e-01 5.83984375e-01 6.99218750e-01 5.71289062e-01
 9.58984375e-01 2.13867188e-01 5.37109375e-02 9.25781250e-01
 3.15429688e-01 6.74804688e-01 4.99023438e-01 9.28710938e-01
 9.40429688e-01 2.44140625e-02 5.41015625e-01 3.42773438e-01
 2.63671875e-02 8.00781250e-02 2.03125000e-01 8.91601562e-01
 5.01953125e-01 5.38085938e-01 2.83203125e-02 1.00585938e-01
 8.76953125e-01 7.25585938e-01 1.13281250e-01 1.49414062e-01
 2.04101562e-01 3.44726562e-01 4.87304688e-01 1.68945312e-01
 5.83007812e-01 7.90039062e-01 1.19140625e-01 4.01367188e-01
 3.90625000e-01 7.82226562e-01 7.68554688e-01 4.88281250e-02
 6.27929688e-01 9.62890625e-01 9.47265625e-02 5.03906250e-01
 8.17382812e-01 7.61718750e-01 9.38476562e-01 2.62695312e-01
 1.95312500e-02 4.86328125e-01 5.85937500e-01 7.31445312e-01
 6.26953125e-01 8.60351562e-01 7.03125000e-02 6.40625000e-01
 5.86914062e-01 2.15820312e-01 2.22656250e-01 1.05468750e-01
 9.17968750e-01 1.71875000e-01 3.22265625e-02 6.47460938e-01
 3.32031250e-02 9.19921875e-01 2.52929688e-01 1.60156250e-01
 4.47265625e-01 2.39257812e-01 6.14257812e-01 2.73437500e-02
 2.81250000e-01 7.56835938e-01 7.66601562e-01 6.21093750e-01
 8.94531250e-01 9.70703125e-01 3.01757812e-01 4.73632812e-01
 8.92578125e-01 8.81835938e-01 5.93750000e-01 4.88281250e-01
 5.27343750e-02 5.48828125e-01 8.27148438e-01 9.34570312e-01
 6.71875000e-01 7.91992188e-01 2.63671875e-01 4.68750000e-02
 3.21289062e-01 5.10742188e-01 8.99414062e-01 8.53515625e-01
 9.58007812e-01 7.65625000e-01 2.73437500e-01 2.34375000e-02
 5.05859375e-01 7.36328125e-01 8.71093750e-01 1.50390625e-01
 8.39843750e-01 3.55468750e-01 3.77929688e-01 6.11328125e-01
 1.57226562e-01 8.58398438e-01 3.80859375e-02 9.47265625e-01
 1.66015625e-01 1.37695312e-01 1.56250000e-01 1.40625000e-01
 1.39648438e-01 1.85546875e-01 3.67187500e-01 1.88476562e-01
 2.40234375e-01 7.12890625e-02 9.68750000e-01 2.47070312e-01
 4.10156250e-01 3.94531250e-01 4.58984375e-01 2.20703125e-01
 2.34375000e-01 8.69140625e-02 2.28515625e-01 2.50976562e-01
 8.40820312e-01 4.56054688e-01 1.53320312e-01 4.29687500e-02
 6.60156250e-01 6.54296875e-02 5.39062500e-01 8.64257812e-01
 9.96093750e-01 5.68359375e-01 6.04492188e-01]
Size
13.0    1885
11.0     197
12.0     196
14.0     193
15.0     184
Name: count, dtype: int64
Installs
unique: [     10000     500000    5000000   50000000     100000      50000
    1000000   10000000       5000  100000000 1000000000       1000
  500000000         50        100        500         10          1
          5          0]
Installs
1000000     1578
10000000    1252
100000      1169
10000       1052
1000         905
Name: count, dtype: int64
Type
unique: <StringArray>
['Free', 'Paid']
Length: 2, dtype: str
Type
Free    10032
Paid      797
Name: count, dtype: int64
Price
unique: [  0.     4.99   3.99   6.99   1.49   2.99   7.99   5.99   3.49   1.99
   9.99   7.49   0.99   9.     5.49  10.    24.99  11.99  79.99  16.99
  14.99   1.    29.99  12.99   2.49  10.99   1.5   19.99  15.99  33.99
  74.99  39.99   3.95   4.49   1.7    8.99   2.     3.88  25.99 399.99
  17.99 400.     3.02   1.76   4.84   4.77   1.61   2.5    1.59   6.49
   1.29   5.    13.99 299.99 379.99  37.99  18.99 389.99  19.9    8.49
   1.75  14.     4.85  46.99 109.99 154.99   3.08   2.59   4.8    1.96
  19.4    3.9    4.59  15.46   3.04   4.29   2.6    3.28   4.6   28.99
   2.95   2.9    1.97 200.    89.99   2.56  30.99   3.61 394.99   1.26
   1.2    1.04]
Price
0.00    10032
0.99      146
2.99      129
1.99       73
4.99       72
Name: count, dtype: int64
Content Rating
unique: <StringArray>
['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+', 'Adults only 18+',
 'Unrated']
Length: 6, dtype: str
Content Rating
Everyone           8704
Teen               1208
Mature 17+          499
Everyone 10+        413
Adults only 18+       3
Name: count, dtype: int64
Genres
unique: <StringArray>
[                   'Art & Design',       'Art & Design;Pretend Play',
         'Art & Design;Creativity', 'Art & Design;Action & Adventure',
                 'Auto & Vehicles',                          'Beauty',
               'Books & Reference',                        'Business',
                          'Comics',               'Comics;Creativity',
 ...
             'Lifestyle;Education',    'Books & Reference;Creativity',
     'Books & Reference;Education',                'Puzzle;Education',
          'Role Playing;Education',        'Role Playing;Brain Games',
              'Strategy;Education',             'Racing;Pretend Play',
        'Communication;Creativity',             'Strategy;Creativity']
Length: 119, dtype: str
Genres
Tools            840
Entertainment    622
Education        548
Medical          463
Business         460
Name: count, dtype: int64
Last_updated_year
unique: [2018 2017 2014 2016 2015 2013 2012 2011 2010]
Last_updated_year
2018    7344
2017    1864
2016     802
2015     459
2014     209
Name: count, dtype: int64
Last_updated_month
unique: [ 1  8  6  3  4  9  7 10 11  5 12  2]
Last_updated_month
7    3161
8    1594
6    1271
5     977
3     666
Name: count, dtype: int64

In [167]:
category = pd.get_dummies(
    df["Category"],
    drop_first=True,
    dtype=int
)
df = pd.concat([df, category], axis=1)

In [168]:
df.drop("Category", axis=1, inplace=True)

In [169]:
df["Genres"].nunique()

119

In [170]:
genres = pd.get_dummies(
    df["Genres"],
    drop_first=True,
    dtype=int
)

df = pd.concat([df, genres], axis=1)

df.drop("Genres", axis=1, inplace=True)

In [171]:
content_rating = pd.get_dummies(
    df["Content Rating"],
    drop_first=True,
    dtype=int
)
df = pd.concat(
    [df, content_rating],
    axis=1
)
df.drop(
    "Content Rating",
    axis=1,
    inplace=True
)

In [172]:
pd.crosstab(df["Type"], df["Price"] == 0)

Price  False  True
Type
Free       0  10032
Paid     797      0

In [173]:
df.drop("Type", axis=1, inplace=True)